### ISSUE TITLE
feat: support for `Metadata.tools` format intrduced with CDX 1.5

### ISSUE THREAD

**Issue by WIStudent** [CycloneDX/cyclonedx-javascript-library#1152]
v1.5 introduced a new format for the `metadata.tools` field: https://cyclonedx.org/docs/1.5/json/#metadata_tools

It seems that `@cyclonedx/cyclonedx-library` currently only supports the legacy format:

https://github.com/CycloneDX/cyclonedx-javascript-library/blob/bdbe727e48a34f6276a4e4a3056b11943fe9e2f4/src/models/metadata.ts#L31
https://github.com/CycloneDX/cyclonedx-javascript-library/blob/bdbe727e48a34f6276a4e4a3056b11943fe9e2f4/src/models/metadata.ts#L43

https://github.com/CycloneDX/cyclonedx-javascript-library/blob/bdbe727e48a34f6276a4e4a3056b11943fe9e2f4/src/models/tool.ts#L25-L59

This prevents other tools like `@cyclonedx/cyclonedx-npm` from creating v1.5 or v1.6 SBOMs with the new `tools` format.

**Comment by jkowalleck** [comment]
The expected result would be a data model `ToolRepository` that could cold 
- multiple instances of `Tool`
- multiple instances of `Component`
- multiple instances of `Service`

This `ToolRepository` would be serialized to JSON/XML like following:
- If at least one `Tool` is included,  
  or the serialization targets a spec before CDX 1.5:  
  any `Component`s and `Service`s are serialized as `Tool`, too.
- else:  
  any `Component`s and `Service`s are serialized as they are

**Comment by WIStudent** [comment]
@jkowalleck I am currently not planing to implement this, I am still evaluating if CycloneDX is the right tool for my usecase. I ran into this problem when I was trying to merge two BOMs that were created with [@cyclonedx/node-npm](https://github.com/CycloneDX/cyclonedx-node-npm) and [cyclonedx-maven-plugin](https://github.com/CycloneDX/cyclonedx-maven-plugin) using the [cyclonedx-cli](https://github.com/CycloneDX/cyclonedx-cli). When creating a v1.6 SBOM, cyclonedx-maven-plugin uses the new `tools` format while @cyclonedx/node-npm uses the legacy format. The cyclonedx-cli is not able to merge new and legacy format correctly. I was looking into @cyclonedx/node-npm to see if there is an option to force the usage of the new format, but realized that @cyclonedx/cyclonedx-library needs to support the new format first.

For now I am telling cyclonedx-maven-plugin to generate a v1.4 SBOM, that way all `tools` fields use the legacy format and can be merged with the cyclonedx-cli.

**Comment by jkowalleck** [comment]
regardles of this very feature request here:

> The cyclonedx-cli is not able to merge new and legacy format correctly. 

Could you report this use case and the expected outcome to [cyclonedx-cli](https://github.com/CycloneDX/cyclonedx-cli)? The project team then might decide whether this is a feature request or a bug report, and how to proceed.

**Comment by WIStudent** [comment]
For completeness: Here is the issue I opened in cyclonedx-cli https://github.com/CycloneDX/cyclonedx-cli/issues/408

**Comment by jkowalleck** [comment]
I will work on a solution. stay tuned 🚀

**Comment by jkowalleck** [comment]
feature preview available as of https://github.com/CycloneDX/cyclonedx-javascript-library/releases/tag/v7.0.0-beta.1
