### ISSUE TITLE
feat: detect simplified repositories from `package.json` like structures

### ISSUE THREAD

**Issue by lal12** [CycloneDX/cyclonedx-javascript-library#517]
The package https://github.com/vercel/ms / https://www.npmjs.com/package/ms specifies `"repository": "vercel/ms"`.
The npm website and cli utility interprets this as a relative url to github.

The SBOM includes the `vcs_url` as `vercel/ms`. So I wonder if `https://github.com` should be prepended in such cases? Maybe with an option to specify a default URL to prepend?

**Comment by jkowalleck** [comment]
@lal12 are you willing to contribute the missing feature based on https://github.com/CycloneDX/cyclonedx-javascript-library/issues/517#issuecomment-1451576296? 

if so, then please follow the guidelines: https://github.com/CycloneDX/cyclonedx-javascript-library/blob/main/CONTRIBUTING.md
current implementation can be found here: https://github.com/CycloneDX/cyclonedx-javascript-library/blob/2488ec684a1f75338cb9f4003e517a72cc1ba414/src/factories/fromNodePackageJson.node.ts#L63

**Comment by jkowalleck** [comment]
The solution will not be to implement the needed normalization here, 
but to enrich the documentations, and make downstream users aware, that they should to needed normalization.
Therefore, the docs will be enhanced, and a new release will make users aware of it.
