### ISSUE TITLE
Error when package-lock.json has no packages listed

### ISSUE THREAD

**Issue by tqheel** [CycloneDX/cyclonedx-javascript-library#519]
When a package-lock.json file is included that has no packages actually defined:
e.g.:
{
  "name": "MyProject",  
  "lockfileVersion": 2,  
  "requires": true,  
  "packages": {}
}

The above causes the following error:

```
/azp/agent/_work/_tool/node/16.19.1/x64/lib/node_modules/@cyclonedx/cdxgen/index.js:1696
      parentComponent.type = "application";
                           ^

TypeError: Cannot set properties of undefined (setting 'type')
    at createNodejsBom (/azp/agent/_work/_tool/node/16.19.1/x64/lib/node_modules/@cyclonedx/cdxgen/index.js:1696:28)
    at async createMultiXBom (/azp/agent/_work/_tool/node/16.19.1/x64/lib/node_modules/@cyclonedx/cdxgen/index.js:3454:15)
    at async Object.createBom (/azp/agent/_work/_tool/node/16.19.1/x64/lib/node_modules/@cyclonedx/cdxgen/index.js:4258:16)
    at async /azp/agent/_work/_tool/node/16.19.1/x64/lib/node_modules/@cyclonedx/cdxgen/bin/cdxgen:156:22
```
Which led me to the following lines in @cyclonedx/cdxgen/index.js:
if (pkgLockFiles && pkgLockFiles.length) {
    manifestFiles = manifestFiles.concat(pkgLockFiles);
    for (let f of pkgLockFiles) {
      if (DEBUG_MODE) {
        console.log(`Parsing ${f}`);
      }
      // Parse package-lock.json if available
      const parsedList = await utils.parsePkgLock(f);
      const dlist = parsedList.pkgList;
      parentComponent = dlist.splice(0, 1)[0];
      parentComponent.type = "application";

In the case of the example package-lock file, parsedList.pkgList is empty.

The workaround is to delete such an unneeded package-lock file, but more resilient error handling for such files would avoid such errors to begin with.

**Comment by jkowalleck** [comment]
@tqheel,

Could it be that you reported to the wrong repository? 
Your issue appeared in `.../node_modules/@cyclonedx/cdxgen/index.js:1696`, so I assume you meat to report to the package [@cyclonedx/cdxgen ](https://www.npmjs.com/package/@cyclonedx/cdxgen).
The issue tracker of this package is here: https://github.com/CycloneDX/cdxgen/issues

**Comment by tqheel** [comment]
Ah, yes. You are correct. Sorry about that.
