### ISSUE TITLE
guarantee correct URLs

### ISSUE THREAD

**Issue by jkowalleck** [CycloneDX/cyclonedx-javascript-library#992]
caused by  https://github.com/CycloneDX/cyclonedx-webpack-plugin/issues/1239#issuecomment-1836447296

An issue exists, where (invalid) URLs like `https://github.com/cssinjs/jss/issues/new?title=[jss-plugin-camel-case]`  cause trouble.
characters `[]` are invalid characters to URL standards. they must be url encoded `%5B%5D`.

possible fix can be done in this library, on normalization time (not in the model).
would not be the first time to fix this ...
see <https://github.com/search?q=repo%3ACycloneDX%2Fcyclonedx-php-library+%255B&type=code>

----

similar to https://github.com/CycloneDX/cyclonedx-php-library/issues/35

have all the XML strings that are `anyURI` somehow fixed before rendering the XML/JSON.
affected elements: 
- component.purl 
- license.url
- externalReterence.url
- and so on ...

according to XML spec the `anyURI` needs to conform to https://www.ietf.org/rfc/rfc2396.txt 

     * @see http://www.w3.org/TR/xmlschema-2/#anyURI
     * @see http://www.datypic.com/sc/xsd/t-xsd_anyURI.html

        /* URIs require that some characters be escaped with their hexadecimal Unicode code point preceded by the %
         * character. This includes non-ASCII characters and some ASCII characters, namely control characters, spaces,
         * and the following characters (unless they are used as deliimiters in the URI): <>#%{}|\^`.
         * [...]
         * The only values that are not accepted are ones that make inappropriate use of reserved characters, such as ones that contain multiple # characters or have % characters that are not followed by two hexadecimal digits.
         * -- as of http://www.datypic.com/sc/xsd/t-xsd_anyURI.html
         */

**Comment by jkowalleck** [comment]
@mLuca ,
do you want to give it a try and implement something that fixes those URLS?

url fixes MUST happen on normalization-time, not in the model.

see as inspiration: https://github.com/search?q=repo%3ACycloneDX%2Fcyclonedx-php-library+%255B&type=code

**Comment by mLuca** [comment]
@jkowalleck I can have a look today.

**Comment by mLuca** [comment]
@jkowalleck I had a look at the code base and grasped a bit of typescript on the way. 
I have written a helper method to be used. At least it doesn't seem to do any harm. Before I go on to write tests and such it would be nice to have a review on this if the direction I am going is ok.

I am new to GitHub, OSS development and such. I don't see how I can create a bugfix-branch to push my changes to? Also I didn't find any styleguide on how to name branches (e.g. "bugfix/992-assert-correct-url" ?)
